### ISSUE TITLE
Bad landing page links

### ISSUE THREAD

**Issue by rweigel** [hapi-server/server-bugs#12]
The links here add an extra "hapi" https://cdaweb.gsfc.nasa.gov/hapi/

**Comment by berniegsfc** [comment]
This is the same as [issue 20](https://git.mysmce.com/spdf/hapi-nand/-/issues/20).

**Comment by berniegsfc** [comment]
I changed the source html page and [committed the change](https://git.smce.nasa.gov/spdf/hapi-nand/-/commit/b5efdcd7e72e6bd95029bbbaa43c7fa1ac02b5ed) to gitlab.  But I didn't (can't) rebuild and deploy the update.  You may want to see the deployed update before closing this.  But it was simple enough that I guess it will eventually work.
