### ISSUE TITLE
New CDAWeb server server

### ISSUE THREAD

**Issue by rweigel** [hapi-server/server-bugs#16]
It looks like https://cdaweb.gsfc.nasa.gov/hapi/ now uses Jeremy's update to Nand's server (based on timestamp at bottom of page). I noticed two issues:

1. The links on that page are broken.
2. The /catalog response no longer has `HAPI` or `status` nodes.

**Comment by jbfaden** [comment]
For the broken links, it looks like https://cdaweb.gsfc.nasa.gov/hapi will have links like https://cdaweb.gsfc.nasa.gov/capabilities which is incorrect.  https://cdaweb.gsfc.nasa.gov/hapi/ will have correct links, and that's probably why we missed this.  Bernie and I had to futz with this page a bit to get things to work.  Note I think this issue has always been the case.

**Comment by jbfaden** [comment]
Also I see what you mean about the catalog response.  Also I'm not sure what would have caused a change there, but I will have a look.

**Comment by berniegsfc** [comment]
We noticed the link issue and I was responding to that when Jeremy beat me.  We hope to have it work with or without the trailing slash but the latest attempt (minutes ago) failed.  Jeremy, if you know how fix it, let me know.  Note that it we add hapi/capabilites on the index.html source, we end up with hapi/hapi/capabilites which is not right either.

**Comment by jbfaden** [comment]
Maybe the thing to do is to make sure .../hapi/ does not respond with the landing page.  I think the spec is a little vague about this, whether .../hapi/ or .../hapi is the landing page.  It should be .../hapi and .../hapi only, I think.

**Comment by berniegsfc** [comment]
Most people expect it to work either way and that's what I'm hoping for.  But I think the trailing slash is more correct when you expect to get an index.html without actually having index.html on the end.

**Comment by rweigel** [comment]
I agree @berniegsfc  - I've been meaning to put a check that both work in the verifier and warning that `/hapi/` should be a 301 to `/hapi`.

**Comment by jbfaden** [comment]
I just went ahead and I handle both in the HapiIntroServlet.  Actually it looks like you've fixed it already Bernie.  Is that right?

**Comment by berniegsfc** [comment]
My change to context.xml didn't help.

**Comment by jbfaden** [comment]
Check that, I think I hadn't pulled and I have something about a HAPI_DIRECTORY macro I put in back in August.

**Comment by jbfaden** [comment]
Bernie, this code is giving me grief with all these library dependencies.  I had this working earlier and then when I updated I thought you'd made the change and reverted my change.  I can't get things to compile to integrate my change again, but the gist of it is to modify the index.html source depending on the "hapi" or "hapi/":

        while (sc.hasNextLine()) {
            line = sc.nextLine();
            line= line.replaceAll("HAPI_DIRECTORY",hapiDirectory);
            if ( line.contains("href") ) {
                if ( "/".equals(endPoint)  ) {
                    line= line.replace("href='hapi/","href='" );
                }
            }
            pw.println(line);
        }

This is in HapiIntroServlet.java.  Does this seem like a reasonable solution?

**Comment by rweigel** [comment]
why not just use relative paths in index.html?

**Comment by jbfaden** [comment]
The bug is that "" and "/" are both handled by the same servlet.  For ".../hapi" the link should be "hapi/catalog", and for ".../hapi/" the link should be "catalog".  It's surprising that this hasn't come up more.

**Comment by rweigel** [comment]
Can you replace trailing slash case with a redirect to ""? Or equivalently respond with trailing slash with

```
<html xmlns="http://www.w3.org/1999/xhtml">    
  <head>      
    <meta http-equiv="refresh" content="0;URL=''" />    
  </head>    
  <body> 
  </body>  
</html> 
````

**Comment by berniegsfc** [comment]
Jeremy, I pasted your code into HapiIntroServlet.java but cancelled the commit when I realized I didn't understand the code.

**Comment by berniegsfc** [comment]
I could easily add a redirect in our http proxy but think the fix probably belongs in the hapi code.  But I'm not sure how to do it in the hapi code.

**Comment by jbfaden** [comment]
I think it's an easy fix, once I figure out why the libraries aren't linking in properly for me.  I'll be working on this now.

**Comment by berniegsfc** [comment]
What does HAPI_DIRECTORY have to do with this page?

**Comment by jbfaden** [comment]
I think it was left over from when I was debugging, and I'll remove it.

**Comment by berniegsfc** [comment]
Why doesn't this servlet have a url-pattern element in the web.xml.  And I think your code breaks the info and data links.

**Comment by jbfaden** [comment]
I'm not sure I follow you.  Isn't it lines 69-76:

    <servlet>
        <servlet-name>hapiintro</servlet-name>
        <servlet-class>hapi.servlet.HapiIntroServlet</servlet-class>
    </servlet>
    <servlet-mapping>
        <servlet-name>hapiintro</servlet-name>
        <url-pattern>/*</url-pattern>
    </servlet-mapping>

There are separate servlets for info and data, aren't there?

**Comment by berniegsfc** [comment]
How did I miss that when I was looking at the url-pattern for the other servlets.  I guess that pattern matches even without the trailing slash on the request url.

**Comment by jbfaden** [comment]
There's way too much going on in this code, I get lost all the time.

**Comment by rweigel** [comment]
My UI code checks for a status of `1200` in the catalog response. Because it is now `200`, it thinks the server returned a bad response.

**Comment by rweigel** [comment]
Maybe run verifier before finalizing commits?

**Comment by jbfaden** [comment]
Whoops, that was my mistake.  The problem with using the validator is that this server has never passed the validator.  I've been running using the validator with the goal that I can decide if something was there all along or not, and I should have thought to run it again on this easy test.  I just had a little whoops forgetting that it was 1200.

**Comment by jbfaden** [comment]
Bernie I've corrected this mistake.  I would run the server for testing as Bob suggests at my site, but I'm missing the jar which provides org.glassfish.jersey.moxy.json.internal, so many of the datasets don't load.

**Comment by berniegsfc** [comment]
That package is in `jersey-media-moxy.jar` which was in the [lib.tar](https://cdaweb.gsfc.nasa.gov/~jsun/lib.tar) that you got.  You must have deleted the jars again.

**Comment by jbfaden** [comment]
Thanks, Bernie.  I figured out Netbeans wasn't bundling all the jars into the .war file.  Now the problem I can't figure out is I keep getting "NoRouteToHostException" , trying to get some of the files like https://cdaweb.gsfc.nasa.gov/pub/data/barrel/l2/2b/mspc.  Maybe this is the problem with closing connections you mentioned, and I'll be looking into it.

**Comment by berniegsfc** [comment]
It's been a [known problem](https://git.smce.nasa.gov/spdf/hapi-nand/-/issues/12) for a long time.
