### ISSUE TITLE
length for Time wrong in MMS1_FGM_SRVY_L2

### ISSUE THREAD

**Issue by rweigel** [hapi-server/server-bugs#2]
A user reported issues with the Python HAPI client. The client could read the csv response, but by default binary is used and the data returned was garbled.

If you look at

https://hapi-server.org/servers/#server=CDAWeb&dataset=MMS1_FGM_SRVY_L2@0&parameters=mms1_fgm_b_gse_srvy_l2&start=2015-09-01T00:00:12Z&stop=2015-09-01T00:00:24.000Z&return=data&format=csv&style=noheader, you can see the timestamps have length of 30. However, the timestamps in the parameter level metadata are reported as having length 24.

**Comment by berniegsfc** [comment]
This is the same as [issue 6](https://git.mysmce.com/spdf/hapi-nand/-/issues/6)

**Comment by berniegsfc** [comment]
A fix has been deployed.
```
$ curl -s "https://cdaweb.gsfc.nasa.gov/hapi/info?id=MMS1_FGM_SRVY_L2@0" | jq '.parameters[]|select(.name | test("Time")?)' 
{
  "name": "Time",
  "type": "isotime",
  "units": "UTC",
  "length": 30,
  "fill": null
}
```
Please verify and close this issue if you are satisfied.
