### ISSUE TITLE
Size for GOES13_EPS-MAGED_1MIN

### ISSUE THREAD

**Issue by rweigel** [hapi-server/server-bugs#3]
At

https://hapi-server.org/servers/#server=CDAWeb&dataset=GOES13_EPS-MAGED_1MIN&parameters=dtc_cor_eflux_stack9&start=2006-06-01T00:00:00Z&stop=2006-06-03T00:00:00.000Z&return=data&format=csv&style=noheader

The metadata claims size=[9,5], but the output is only 5 columns.

Direct link to data (also given on above page):

https://cdaweb.gsfc.nasa.gov/hapi/data?id=GOES13_EPS-MAGED_1MIN&parameters=dtc_cor_eflux_stack9&time.min=2006-06-01T00:00:00Z&time.max=2006-06-03T00:00:00.000Z

**Comment by berniegsfc** [comment]
This is the same as [issue 7](https://git.mysmce.com/spdf/hapi-nand/-/issues/7).

**Comment by berniegsfc** [comment]
Bob, can you verify that this is fixed so it can be closed?  Tami [says that it is](https://git.mysmce.com/spdf/hapi-nand/-/issues/7#note_8586).

**Comment by rweigel** [comment]
The columns part is fixed. I noticed that the time string is more than 24, similar to #2

**Comment by berniegsfc** [comment]
Let's close this one and the corresponding one in gitlab.  The time string must be the same issue as #2.
