### ISSUE TITLE
Pre-DMSP 16 data

### ISSUE THREAD

**Issue by rweigel** [hapi-server/server-bugs#4]
From https://helionauts.org/t/dmsp-data-source/906:

> I am looking for a good source for DMSP data—specifically magnetometer (ssm) and particle (ssj) data—with the biggest time range possible, but at least from 2000–2022.
>
> A data product with ~1 minute cadence is preferred.
>
> The CDAWeb data available here from the HAPI server only covers a small portion of that time range: [Index of /pub/data/dmsp 1](https://cdaweb.gsfc.nasa.gov/pub/data/dmsp/)
>
> The data from NOAA here has a bigger range, but is a little more difficult to access programatically: [Index of /dmsp/data](https://satdat.ngdc.noaa.gov/dmsp/data/)
>
> One site says selected products goes to http://cedar.openmadrigal.org/ but I only found “DMSP-Auroral Boundary Index [1982-2016]”.
>
> What is the best source for DMSP ssm and ssj data through time? I am hoping there is an easy-to-access source that I don’t know about.

At https://hapi-server.org/servers/#server=CDAWeb, I only see DMSP 16, 17, and 18.

**Comment by berniegsfc** [comment]
This doesn't appear to be a cdaweb hapi implementation issue because the same limited dmsp data is shown by [cdaweb](https://cdaweb.gsfc.nasa.gov/) and the associated web services.  I suggest contacting the spdf data acquisition people at [spdf support](mailto:NASA-SPDF-Support@nasa.onmicrosoft.com) and asking why only a limited amout of data is available.

**Comment by rweigel** [comment]
Thanks. Will close after posting SPDF response.

**Comment by jvandegriff** [comment]
I will also ask around at APL, since we have done work on the SSJ data over the years (I worked on a display tool for it years ago). I've got two people I can ask initially, and I'll report back what they say.

**Comment by rweigel** [comment]
@jbfaden Does Autoplot pick up these data? My understanding is that it does not go through the web services.

**Comment by rweigel** [comment]
From [SPDF-Support](NASA-SPDF-Support@nasa.onmicrosoft.com)

> Hi Bob – we’ve worked on/off for years and more recently with Rob Redmond and Liam Kilcommons to get SSJ and SSM data into the SPDF and CDAWeb.  We’ll have to ask him again about this effort, the next time we meet (August 16).  We haven’t seen anything from NOAA for these in quite a while (we have our auto-ingest s/w checking their directories daily).  What we have put in CDAWeb is still just our “test” view awaiting approval (and more data) from Rob and Liam.

**Comment by jbfaden** [comment]
Autoplot uses the web services to get the list of CDF files to download, and I just see 
data from DMSP-16, 17 and 18. DMSP-16 is available from 2009 through 2015.

**Comment by jvandegriff** [comment]
APL has a lot of SSJ data, some of which still needs calibrating.  I"m trying to get the folks here to submit a proposal to upgrade it, and I think that may happen, but on a time scale of about a year, assuming of course that the proposal gets funded.
